version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - BUILD=${BUILD:-dev}
        - PORT=${PORT:-4200}
    restart: always
    ports:
      - '127.0.0.1:${PORT}:80'
