import sys
sys.stdout.reconfigure(encoding='utf-8')

with open('C:/Users/Drako/Desktop/DEAD-CAMERA/dcs-front/src/app/modules/studio/studio/ui/index-studio/index-studio.ts', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find the start
start_idx = None
for i, line in enumerate(lines):
    if 'Breadcrumb event handlers' in line and '─' in line:
        start_idx = i
        break

if start_idx is None:
    print('ERROR: start marker not found')
    sys.exit(1)

# The end is the blank line after 'private reloadShots' closing brace
# Find reloadShots
reload_idx = None
for i in range(start_idx, len(lines)):
    if 'private reloadShots' in lines[i]:
        reload_idx = i
        break

if reload_idx is None:
    print('ERROR: reloadShots not found')
    sys.exit(1)

# Find the closing } of reloadShots + the blank line after it
for i in range(reload_idx, len(lines)):
    if lines[i].strip() == '}' and i+1 < len(lines) and lines[i+1].strip() == '':
        end_idx = i + 1  # include the blank line
        break

if 'end_idx' not in dir():
    print('ERROR: end not found')
    sys.exit(1)

print(f'Replacing lines {start_idx+1} to {end_idx+1}')

new_block = [
    '  // ── Breadcrumb event handlers ──────────────────────────────────────────\n',
    '\n',
    '  protected loadProjects(): void {\n',
    '    this.navLoadingProjects.set(true);\n',
    '    this.projectsApi.listProjects().subscribe((res) => {\n',
    '      this.navLoadingProjects.set(false);\n',
    '      if (!res.error && res.data) {\n',
    '        this.navProjects.set(res.data.sort((a, b) => a.name.localeCompare(b.name)));\n',
    '        // If restoring, trigger the cascade after projects load\n',
    '        if (this.restoring() && this.savedNav) {\n',
    '          this.restoreAfterProjects();\n',
    '        }\n',
    '      }\n',
    '    });\n',
    '  }\n',
    '\n',
    '  protected onNavProjectChange(projectId: string | null): void {\n',
    '    this.studio.resetStudio();\n',
    '    this.navChapters.set([]);\n',
    '    this.navScenes.set([]);\n',
    '    this.navShots.set([]);\n',
    '    this.navSelectedChapterId.set(null);\n',
    '    this.navSelectedSceneId.set(null);\n',
    '    this.navSelectedScene.set(null);\n',
    '    this.navSelectedShotId.set(null);\n',
    '    this.persistNav();\n',
    '    if (projectId) {\n',
    '      this.loadChapters(projectId);\n',
    '    }\n',
    '  }\n',
    '\n',
    '  /** Load chapters for a project and auto-select if appropriate. */\n',
    '  private loadChapters(projectId: string): void {\n',
    '    this.navLoadingChapters.set(true);\n',
    '    this.projectsApi.listChapters(projectId).subscribe((res) => {\n',
    '      this.navLoadingChapters.set(false);\n',
    '      if (!res.error && res.data) {\n',
    '        const items = res.data\n',
    '          .sort((a, b) => a.name.localeCompare(b.name))\n',
    '          .map((c) => ({\n',
    '            id: c.id,\n',
    '            number: c.number,\n',
    '            name: c.name,\n',
    '            label: `EP${String(c.number).padStart(2, \'0\')} \\u2014 ${c.name}`,\n',
    '          }));\n',
    '        this.navChapters.set(items);\n',
    '        this.autoSelectChapter(items);\n',
    '      }\n',
    '    });\n',
    '  }\n',
    '\n',
    '  /** After chapters load, select the right one (restored, auto, or none). */\n',
    '  private autoSelectChapter(items: BreadcrumbOption[]): void {\n',
    '    const saved = this.savedNav;\n',
    '    if (this.restoring() && saved?.chapterId) {\n',
    '      const match = items.find((c) => c.id === saved.chapterId);\n',
    '      if (match) {\n',
    '        this.navSelectedChapterId.set(match.id);\n',
    '        this.handleChapterSelected(match.id);\n',
    '        return;\n',
    '      }\n',
    '    }\n',
    '    if (!this.restoring() && items.length === 1) {\n',
    '      this.navSelectedChapterId.set(items[0].id);\n',
    '      this.handleChapterSelected(items[0].id);\n',
    '    }\n',
    '  }\n',
    '\n',
    '  /** Called when a chapter is selected (user or auto). */\n',
    '  private handleChapterSelected(chapterId: string): void {\n',
    '    this.studio.resetStudio();\n',
    '    this.navScenes.set([]);\n',
    '    this.navShots.set([]);\n',
    '    this.navSelectedSceneId.set(null);\n',
    '    this.navSelectedScene.set(null);\n',
    '    this.navSelectedShotId.set(null);\n',
    '    this.persistNav();\n',
    '    const projectId = this.navSelectedProjectId();\n',
    '    if (projectId) {\n',
    '      this.loadScenes(projectId, chapterId);\n',
    '    }\n',
    '  }\n',
    '\n',
    '  protected onNavChapterChange(chapterId: string | null): void {\n',
    '    if (chapterId) {\n',
    '      this.handleChapterSelected(chapterId);\n',
    '    }\n',
    '  }\n',
    '\n',
    '  /** Load scenes for a chapter and auto-select if appropriate. */\n',
    '  private loadScenes(projectId: string, chapterId: string): void {\n',
    '    this.navLoadingScenes.set(true);\n',
    '    this.projectsApi.listScenes(projectId, chapterId).subscribe((res) => {\n',
    '      this.navLoadingScenes.set(false);\n',
    '      if (!res.error && res.data) {\n',
    '        const items = res.data\n',
    '          .sort((a, b) => a.name.localeCompare(b.name))\n',
    '          .map((s) => ({\n',
    '            id: s.id,\n',
    '            number: s.number,\n',
    '            name: s.name,\n',
    '            label: `SC${String(s.number).padStart(2, \'0\')} \\u2014 ${s.name}`,\n',
    '          }));\n',
    '        this.navScenes.set(items);\n',
    '        this.autoSelectScene(items);\n',
    '      }\n',
    '    });\n',
    '  }\n',
    '\n',
    '  /** After scenes load, select the right one (restored, auto, or none). */\n',
    '  private autoSelectScene(items: BreadcrumbOption[]): void {\n',
    '    const saved = this.savedNav;\n',
    '    if (this.restoring() && saved?.sceneId) {\n',
    '      const match = items.find((s) => s.id === saved.sceneId);\n',
    '      if (match) {\n',
    '        this.navSelectedSceneId.set(match.id);\n',
    '        this.handleSceneSelected(match.id);\n',
    '        return;\n',
    '      }\n',
    '    }\n',
    '    if (!this.restoring() && items.length === 1) {\n',
    '      this.navSelectedSceneId.set(items[0].id);\n',
    '      this.handleSceneSelected(items[0].id);\n',
    '    }\n',
    '  }\n',
    '\n',
    '  /** Called when a scene is selected (user or auto). */\n',
    '  private handleSceneSelected(sceneId: string): void {\n',
    '    this.studio.resetStudio();\n',
    '    this.navShots.set([]);\n',
    '    this.navSelectedShotId.set(null);\n',
    '    this.persistNav();\n',
    '    const scene = this.navScenes().find((s) => s.id === sceneId);\n',
    '    if (scene) {\n',
    '      this.navSelectedScene.set({ id: scene.id, number: scene.number, name: scene.name });\n',
    '    }\n',
    '    const projectId = this.navSelectedProjectId();\n',
    '    const chapterId = this.navSelectedChapterId();\n',
    '    if (projectId && chapterId) {\n',
    '      this.loadShots(projectId, chapterId, sceneId);\n',
    '    }\n',
    '  }\n',
    '\n',
    '  protected onNavSceneChange(sceneId: string | null): void {\n',
    '    if (sceneId) {\n',
    '      this.handleSceneSelected(sceneId);\n',
    '    } else {\n',
    '      this.studio.resetStudio();\n',
    '      this.navShots.set([]);\n',
    '      this.navSelectedShotId.set(null);\n',
    '      this.navSelectedScene.set(null);\n',
    '      this.persistNav();\n',
    '    }\n',
    '  }\n',
    '\n',
    '  /** Load shots for a scene and auto-select if appropriate. */\n',
    '  private loadShots(projectId: string, chapterId: string, sceneId: string): void {\n',
    '    this.navLoadingShots.set(true);\n',
    '    this.projectsApi.listShots(projectId, chapterId, sceneId).subscribe((res) => {\n',
    '      this.navLoadingShots.set(false);\n',
    '      if (!res.error && res.data) {\n',
    '        const items = res.data\n',
    '          .sort((a, b) => a.name.localeCompare(b.name))\n',
    '          .map((sh) => ({\n',
    '            id: sh.id,\n',
    '            number: sh.number,\n',
    '            name: sh.name,\n',
    '            label: `SH${String(sh.number).padStart(2, \'0\')} \\u2014 ${sh.name}`,\n',
    '          }));\n',
    '        this.navShots.set(items);\n',
    '        this.autoSelectShot(items);\n',
    '      }\n',
    '    });\n',
    '  }\n',
    '\n',
    '  /** After shots load, select the right one (restored, auto, or none). */\n',
    '  private autoSelectShot(items: BreadcrumbOption[]): void {\n',
    '    const saved = this.savedNav;\n',
    '    if (this.restoring() && saved?.shotId) {\n',
    '      const match = items.find((sh) => sh.id === saved.shotId);\n',
    '      if (match) {\n',
    '        this.navSelectedShotId.set(match.id);\n',
    '        this.onNavShotChange(match.id);\n',
    '        return;\n',
    '      }\n',
    '    }\n',
    '    if (!this.restoring() && items.length === 1) {\n',
    '      this.navSelectedShotId.set(items[0].id);\n',
    '      this.onNavShotChange(items[0].id);\n',
    '    }\n',
    '  }\n',
    '\n',
    '  protected onNavShotChange(shotId: string | null): void {\n',
    '    if (!shotId) {\n',
    '      this.studio.resetStudio();\n',
    '      this.persistNav();\n',
    '      return;\n',
    '    }\n',
    '    const shot = this.navShots().find((s) => s.id === shotId);\n',
    '    if (shot) {\n',
    '      this.startSessionWithShot(shot);\n',
    '      this.persistNav();\n',
    '    }\n',
    '  }\n',
    '\n',
    '  /** Reload shots list for the current scene. */\n',
    '  private reloadShots(): void {\n',
    '    const projectId = this.navSelectedProjectId();\n',
    '    const chapterId = this.navSelectedChapterId();\n',
    '    const sceneId = this.navSelectedSceneId();\n',
    '    if (!projectId || !chapterId || !sceneId) return;\n',
    '\n',
    '    this.navLoadingShots.set(true);\n',
    '    this.projectsApi.listShots(projectId, chapterId, sceneId).subscribe((res) => {\n',
    '      this.navLoadingShots.set(false);\n',
    '      if (!res.error && res.data) {\n',
    '        this.navShots.set(\n',
    '          res.data\n',
    '            .sort((a, b) => a.name.localeCompare(b.name))\n',
    '            .map((sh) => ({\n',
    '              id: sh.id,\n',
    '              number: sh.number,\n',
    '              name: sh.name,\n',
    '              label: `SH${String(sh.number).padStart(2, \'0\')} \\u2014 ${sh.name}`,\n',
    '            })),\n',
    '        );\n',
    '        // Auto-select if the previously selected shot is now in the list\n',
    '        const saved = this.savedNav;\n',
    '        if (saved?.shotId) {\n',
    '          const match = this.navShots().find((sh) => sh.id === saved.shotId);\n',
    '          if (match) {\n',
    '            this.navSelectedShotId.set(match.id);\n',
    '            this.onNavShotChange(match.id);\n',
    '          }\n',
    '        }\n',
    '      }\n',
    '    });\n',
    '  }\n',
    '\n',
    '  /** Persist current breadcrumb selection to localStorage. */\n',
    '  private persistNav(): void {\n',
    '    const projectId = this.navSelectedProjectId();\n',
    '    if (!projectId) {\n',
    '      localStorage.removeItem(LS_KEY);\n',
    '      return;\n',
    '    }\n',
    '    const scene = this.navSelectedScene();\n',
    '    const selection: StoredNavSelection = {\n',
    '      projectId,\n',
    '      chapterId: this.navSelectedChapterId(),\n',
    '      sceneId: this.navSelectedSceneId(),\n',
    '      shotId: this.navSelectedShotId(),\n',
    '      sceneNumber: scene?.number,\n',
    '      sceneName: scene?.name,\n',
    '    };\n',
    '    localStorage.setItem(LS_KEY, JSON.stringify(selection));\n',
    '  }\n',
    '\n',
    '  /** Start restoring a previous selection from localStorage. */\n',
    '  private startRestoring(): void {\n',
    '    const raw = localStorage.getItem(LS_KEY);\n',
    '    if (!raw) return;\n',
    '    try {\n',
    '      const saved = JSON.parse(raw) as StoredNavSelection;\n',
    '      if (!saved.projectId) return;\n',
    '      this.savedNav = saved;\n',
    '      this.restoring.set(true);\n',
    '      // Projects load is already in progress (called from ngOnInit),\n',
    '      // so restoration continues in loadProjects() callback.\n',
    '    } catch {\n',
    '      localStorage.removeItem(LS_KEY);\n',
    '    }\n',
    '  }\n',
    '\n',
    '  /** Continue restoration after projects have loaded. */\n',
    '  private restoreAfterProjects(): void {\n',
    '    const saved = this.savedNav;\n',
    '    if (!saved) return;\n',
    '\n',
    '    // Find the project in the loaded list\n',
    '    const project = this.navProjects().find((p) => p.id === saved.projectId);\n',
    '    if (!project) {\n',
    '      // Saved project no longer exists — bail out\n',
    '      this.restoring.set(false);\n',
    '      this.savedNav = null;\n',
    '      localStorage.removeItem(LS_KEY);\n',
    '      return;\n',
    '    }\n',
    '\n',
    '    // Select the project (this will cascade to load chapters)\n',
    '    this.navSelectedProjectId.set(saved.projectId);\n',
    '    this.loadChapters(saved.projectId);\n',
    '  }\n',
    '\n',
]

lines[start_idx:end_idx+1] = new_block

with open('C:/Users/Drako/Desktop/DEAD-CAMERA/dcs-front/src/app/modules/studio/studio/ui/index-studio/index-studio.ts', 'w', encoding='utf-8') as f:
    f.writelines(lines)

print(f'OK - replaced {end_idx+1 - start_idx} lines with {len(new_block)} lines')
